fixed commit-version

diff --git a/commit-version b/commit-version
--- a/commit-version
+++ b/commit-version
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 set -e
+if [[ $# -eq 0 ]] ; then
+    echo 'Versioning arguments are required.'
+    exit 1
+fi
 $(npm bin)/gulp
 git add -f lib-* production.js
 git commit -m 'prepublish build'
